configfile: "configs/config.yaml"

include: "side.smk"

rule all:
  input:
    f'{config["testdir_name"]}/out.txt'
    f'{config["testdir_name"]}/python.done'

rule samplerule:
  output:
    of=f'{config["testdir_name"]}/out.txt'
  input:
  shell:
    "echo 'OK' > {output.of}"

