name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref to build and publish"
        type: string
        required: false
  workflow_call:
    inputs:
      ref:
        description: "Git ref to build and publish"
        type: string
        required: true

env:
  UV_VERSION: "0.11.6"

jobs:
  build-and-publish:
    name: Build & Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/snakemk_util
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Install uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.14

      - name: Build package
        run: uv build --sdist --wheel --out-dir dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
        with:
          packages-dir: dist
